---
title: "Massachusetts Premature Mortality Analysis"
author: "Rachel Nethery"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: pdf_document
classoption: landscape
---

```{r loadlibs,include=FALSE}
library(maptools)
library(spdep)
library(MASS)
library(msm)
library(tigris)
library(CARBayes)
library(knitr)
library(kableExtra)
library(lme4)

blank_lines <- function(n = 10){cat(rep("&nbsp;  ",n), sep="\n")}
```

```{r setup, include=FALSE,cache=TRUE}
##################################
## premature mortality analysis ##
##################################

library(maptools)
library(spdep)
library(MASS)
library(msm)
library(tigris)
library(CARBayes)
library(knitr)
library(kableExtra)

setwd("/Users/rachel/Dropbox/waller/rachel/BARI")

nburn<-10000
nsamp<-20000

set.seed(2)


#############################
## read in the merged data ##
#############################

load('data_cleaned/merged_pm_denom_cov_data_fromLF.RData')

adat<-adat[which(!(adat$race %in% c('total','hispanic'))),]

## add numeric black/white indicator ##
adat$bw_ind<-0
adat$bw_ind[which(adat$race=='black')]<-1

## remove missing covariates ##
adat<-adat[complete.cases(adat[,c('bw_ind','acs_pov_pct','acs_ice_inc')]),]

## sort by geoid ##
adat<-adat[order(adat$GEOID),]

N<-nrow(adat)
Nct<-length(unique(adat$GEOID))

########################################
## adjacency matrix for census tracts ##
########################################

## extract shapefile ##
ma_shp<-tracts(state = 'MA',year=2010)

## get adjacency matrix ##
foo = poly2nb(ma_shp, queen=TRUE, row.names=ma_shp@data$GEOID10)
W=nb2mat(foo,style='B')

#######################################################################
## align ordering of adjacency matrix and covariates/population data ##
#######################################################################

## census tracts in W with matches in the data ##
tractrm<-which(rownames(W) %in% as.character(adat$GEOID))

W<-W[tractrm,tractrm]

W<-W[order(as.numeric(rownames(W))),order(as.numeric(rownames(W)))]

identical(unique(as.character(adat$GEOID)),rownames(W))

####################################################
## fit CAR models with census/acs/dp denominators ##
####################################################

adat$ind.area<-as.numeric(as.factor(adat$GEOID))
adat$ind.re<-as.factor(1:N)

covars<-c('acs_pov_pct','acs_ice_inc','ice_racewb')
yrs<-c('1yr','5yr')

tab_list<-list()
for (j in 1:length(covars)){
  for (i in yrs){
    tab_out<-data.frame(1:3)
    for (k in c('ce','dp','acs')){
       
      if (grepl('racewb',covars[j])==T){
        fmla<-as.formula(paste0('ndeaths_',i,'~bw_ind+',k,'_',covars[j],'+offset(log(',k,'_',i,'_istexp))'))
      } else{
        fmla<-as.formula(paste0('ndeaths_',i,'~bw_ind+',covars[j],'+offset(log(',k,'_',i,'_istexp))'))
      }
      
    temp<-subset(adat,eval(parse(text =paste0(k,'_',i,'_pop')))>0)
    Wnew<-W[unique(adat$ind.area[which(adat[[paste0(k,'_',i,'_pop')]]>0)]),
            unique(adat$ind.area[which(adat[[paste0(k,'_',i,'_pop')]]>0)])]
    
    fit_bw<-S.CARmultilevel(fmla,family="poisson",
                                 data=temp,
                                 ind.area=as.numeric(as.factor(temp$GEOID)),
                                 ind.re=as.factor(1:nrow(temp)),
                                 W=Wnew,
                                 burnin=nburn,n.sample=nsamp)
    sum_bw<-as.data.frame(exp(fit_bw[[1]][1:3,1:3]))
    rownames(sum_bw)<-1:3
    tab_out<-cbind(tab_out,sum_bw)
    
    temp[[paste0('fitted_',k,'_',i)]]<-fit_bw$fitted/temp[[paste0(k,'_',i,'_istexp')]]
    
    adat<-merge(adat,data.frame(temp[,c('GEOID','race',paste0('fitted_',k,'_',i))]),by=c('GEOID','race'),all.x=T)

    }
    
    tab_out<-tab_out[,-1]
        
    names(tab_out)<-rep(c('IRR','Lower CL','Upper CL'),3)
    rownames(tab_out)<-c('Intercept','Black (vs NH-White)',covars[j])
 
    tab_list<-c(tab_list,list(round(tab_out,2)))
  }
}
    
save(adat,file='/Users/rachel/Dropbox/waller/rachel/BARI/pm_analyses/output/smoothed_SMRs_ma_bw.RData')

```

```{r comp_setup,include=F,cache=TRUE}
fe_mod<-glm(ndeaths_5yr~bw_ind+offset(log(dp_5yr_istexp)),data=adat,family=poisson())
fe_tab<-paste(round(exp(coef(fe_mod)),3),paste0('(',apply( round(exp(confint(fe_mod)),3) , 1 , paste0 , collapse = "," ),')'))

re_mod<-glmer(ndeaths_5yr~bw_ind + offset(log(adat$ce_5yr_istexp)) + (1|GEOID) , data = adat, family = poisson)
re_tab<-paste(round(exp(summary(re_mod)$coefficients[,1]),3),paste0('(',apply( round(exp(confint(re_mod)[2:3,]),3) , 1 , paste0 , collapse = "," ),')'))

temp<-subset(adat,ce_5yr_pop>0)
Wnew<-W[unique(adat$ind.area[which(adat[['ce_5yr_pop']]>0)]),
        unique(adat$ind.area[which(adat[['ce_5yr_pop']]>0)])]

sp_mod<-S.CARmultilevel(ndeaths_5yr~bw_ind + offset(log(ce_5yr_istexp)),family="poisson",
                        data=temp,
                        ind.area=as.numeric(as.factor(temp$GEOID)),
                        ind.re=as.factor(1:nrow(temp)),
                        W=Wnew,
                        burnin=nburn,n.sample=nsamp)
sp_tab<-paste(round(exp(sp_mod[[1]][1:2,1]),3),paste0('(',apply( round(exp(sp_mod[[1]][1:2,2:3]),3) , 1 , paste0 , collapse = "," ),')'))

comp_tab<-data.frame(fe_tab,re_tab,sp_tab)
rownames(comp_tab)<-c('Intercept','Black (vs NH-White)')
names(comp_tab)<-c('GLM','Mixed','Spatial')

```

# 1. Black vs NH-White
&nbsp;

## 1.1 Compare Spatial Model, Mixed Model (non-spatial), and GLM using Census Only

```{r comp_out,echo=FALSE,results='asis'}
kable(comp_tab)
```

&nbsp;
&nbsp;

## 1.2 All Spatial Model Results

```{r outputbw, echo=FALSE,results='asis'}

varnames<-c('Percent Poverty','ICE Income','ICE Race')

## collapse point estimates and CIs in the tables ##
tab_list_clean<-lapply(tab_list, FUN=function(x) data.frame('Census'=paste(x[,1],paste0('(',apply( x[ ,2:3] , 1 , paste0 , collapse = "," ),')')),
                                                            'DP'=paste(x[,4],paste0('(',apply( x[ ,5:6] , 1 , paste0 , collapse = "," ),')')),
                                                            'ACS'=paste(x[,7],paste0('(',apply( x[ ,8:9] , 1 , paste0 , collapse = "," ),')')),
                                                            row.names=rownames(x)))

ind<-seq(1,length(tab_list_clean),2)
for (j in 1:(length(tab_list_clean)/2)){
    cat(paste0('### 1.2.',j,' Adjusted for ',varnames[j],'\n'))
    x<-kable(cbind(tab_list_clean[[ind[j]]],tab_list_clean[[ind[j]+1]]))
    print(add_header_above(x, c(' '=1,'1-Year Rates'=3,"5-Year Rates" = 3)))
}
```


```{r setup2, include=FALSE,cache=TRUE}
#############################
## read in the merged data ##
#############################
setwd("/Users/rachel/Dropbox/waller/rachel/BARI")

load('data_cleaned/merged_pm_denom_cov_data_fromLF.RData')

adat<-adat[which(!(adat$race %in% c('total','black'))),]

## add numeric black/white indicator ##
adat$bw_ind<-0
adat$bw_ind[which(adat$race=='hispanic')]<-1

## remove missing covariates ##
adat<-adat[complete.cases(adat[,c('bw_ind','acs_pov_pct','acs_ice_inc')]),]

## sort by geoid ##
adat<-adat[order(adat$GEOID),]

N<-nrow(adat)
Nct<-length(unique(adat$GEOID))

########################################
## adjacency matrix for census tracts ##
########################################

## extract shapefile ##
ma_shp<-tracts(state = 'MA',year=2010)

## get adjacency matrix ##
foo = poly2nb(ma_shp, queen=TRUE, row.names=ma_shp@data$GEOID10)
W=nb2mat(foo,style='B')

#######################################################################
## align ordering of adjacency matrix and covariates/population data ##
#######################################################################

## census tracts in W with matches in the data ##
tractrm<-which(rownames(W) %in% as.character(adat$GEOID))

W<-W[tractrm,tractrm]

W<-W[order(as.numeric(rownames(W))),order(as.numeric(rownames(W)))]

identical(unique(as.character(adat$GEOID)),rownames(W))

####################################################
## fit CAR models with census/acs/dp denominators ##
####################################################

adat$ind.area<-as.numeric(as.factor(adat$GEOID))
adat$ind.re<-as.factor(1:N)

covars<-c('acs_pov_pct','acs_ice_inc','ice_racewb')
yrs<-c('1yr','5yr')

tab_list<-list()
for (j in 1:length(covars)){
  for (i in yrs){
    tab_out<-data.frame(1:3)
    for (k in c('ce','dp','acs')){
       
      if (grepl('racewb',covars[j])==T){
        fmla<-as.formula(paste0('ndeaths_',i,'~bw_ind+',k,'_',covars[j],'+offset(log(',k,'_',i,'_istexp))'))
      } else{
        fmla<-as.formula(paste0('ndeaths_',i,'~bw_ind+',covars[j],'+offset(log(',k,'_',i,'_istexp))'))
      }
      
    temp<-subset(adat,eval(parse(text =paste0(k,'_',i,'_pop')))>0)
    Wnew<-W[unique(adat$ind.area[which(adat[[paste0(k,'_',i,'_pop')]]>0)]),
            unique(adat$ind.area[which(adat[[paste0(k,'_',i,'_pop')]]>0)])]
    
    fit_hw<-S.CARmultilevel(fmla,family="poisson",
                                 data=temp,
                                 ind.area=as.numeric(as.factor(temp$GEOID)),
                                 ind.re=as.factor(1:nrow(temp)),
                                 W=Wnew,
                                 burnin=nburn,n.sample=nsamp)
    sum_hw<-as.data.frame(exp(fit_hw[[1]][1:3,1:3]))
    rownames(sum_hw)<-1:3
    tab_out<-cbind(tab_out,sum_hw)
    
    temp[[paste0('fitted_',k,'_',i)]]<-fit_hw$fitted/temp[[paste0(k,'_',i,'_istexp')]]
    
    adat<-merge(adat,data.frame(temp[,c('GEOID','race',paste0('fitted_',k,'_',i))]),by=c('GEOID','race'),all.x=T)

    }
    
    tab_out<-tab_out[,-1]
        
    names(tab_out)<-rep(c('IRR','Lower CL','Upper CL'),3)
    rownames(tab_out)<-c('Intercept','Hispanic (vs NH-White)',covars[j])
   
    tab_list<-c(tab_list,list(round(tab_out,2)))
  }
}

save(adat,file='/Users/rachel/Dropbox/waller/rachel/BARI/pm_analyses/output/smoothed_SMRs_ma_hw.RData')


```

```{r comp_setup2,include=F,cache=TRUE}
fe_mod<-glm(ndeaths_5yr~bw_ind+offset(log(dp_5yr_istexp)),data=adat,family=poisson())
fe_tab<-paste(round(exp(coef(fe_mod)),3),paste0('(',apply( round(exp(confint(fe_mod)),3) , 1 , paste0 , collapse = "," ),')'))

re_mod<-glmer(ndeaths_5yr~bw_ind + offset(log(adat$ce_5yr_istexp)) + (1|GEOID) , data = adat, family = poisson)
re_tab<-paste(round(exp(summary(re_mod)$coefficients[,1]),3),paste0('(',apply( round(exp(confint(re_mod)[2:3,]),3) , 1 , paste0 , collapse = "," ),')'))

temp<-subset(adat,ce_5yr_pop>0)
Wnew<-W[unique(adat$ind.area[which(adat[['ce_5yr_pop']]>0)]),
        unique(adat$ind.area[which(adat[['ce_5yr_pop']]>0)])]

sp_mod<-S.CARmultilevel(ndeaths_5yr~bw_ind + offset(log(ce_5yr_istexp)),family="poisson",
                        data=temp,
                        ind.area=as.numeric(as.factor(temp$GEOID)),
                        ind.re=as.factor(1:nrow(temp)),
                        W=Wnew,
                        burnin=nburn,n.sample=nsamp)
sp_tab<-paste(round(exp(sp_mod[[1]][1:2,1]),3),paste0('(',apply( round(exp(sp_mod[[1]][1:2,2:3]),3) , 1 , paste0 , collapse = "," ),')'))

comp_tab<-data.frame(fe_tab,re_tab,sp_tab)
rownames(comp_tab)<-c('Intercept','Hispanic (vs NH-White)')
names(comp_tab)<-c('GLM','Mixed','Spatial')

```

&nbsp;
&nbsp;

# 2. Hispanic vs NH-White
&nbsp;

## 2.1 Compare Spatial Model, Mixed Model (non-spatial), and GLM using Census Only

```{r comp_out2,echo=FALSE,results='asis'}
kable(comp_tab)
```

&nbsp;
&nbsp;

## 2.2 All Spatial Model Results

```{r outputhw,echo=F,results='asis'}
## collapse point estimates and CIs in the tables ##
tab_list_clean<-lapply(tab_list, FUN=function(x) data.frame('Census'=paste(x[,1],paste0('(',apply( x[ ,2:3] , 1 , paste0 , collapse = "," ),')')),
                                                            'DP'=paste(x[,4],paste0('(',apply( x[ ,5:6] , 1 , paste0 , collapse = "," ),')')),
                                                            'ACS'=paste(x[,7],paste0('(',apply( x[ ,8:9] , 1 , paste0 , collapse = "," ),')')),
                                                            row.names=rownames(x)))

ind<-seq(1,length(tab_list_clean),2)
for (j in 1:(length(tab_list_clean)/2)){
    cat(paste0('### 2.2.',j,' Adjusted for ',varnames[j],'\n'))
    x<-kable(cbind(tab_list_clean[[ind[j]]],tab_list_clean[[ind[j]+1]]))
    print(add_header_above(x, c(' '=1,'1-Year Rates'=3,"5-Year Rates" = 3)))
} 
```
